.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MPDFINDBY" "1" "March 2012" "" ""
.
.SH "NAME"
\fBmpdfindby\fR \- find and print matching songs
.
.SH "SYNOPSIS"
\fBmpdfindby [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBmpdfindby\fR is a simple utility that, given some information about some songs (i\.e\. title, artist and album), prints to \fBSTDOUT\fR the matching entries in the current playlist or in the whole database\. The output format is configurable\.
.
.P
Optionally a new playlist can be created out of the matching songs\.
.
.SH "OPTIONS"
\fB\-A, \-\-all\fR
.
.P
\~\~\~\~\~\~ Match all the songs\.
.
.P
\fB\-t, \-\-title\fR
.
.P
\~\~\~\~\~\~ The song title\.
.
.P
\fB\-r, \-\-artist\fR
.
.P
\~\~\~\~\~\~ The song artist\.
.
.P
\fB\-b, \-\-album\fR
.
.P
\~\~\~\~\~\~ The song album\.
.
.P
\fB\-f, \-\-format\fR
.
.P
\~\~\~\~\~\~ The output format string\. \fB%t\fR is replaced by the song title, \fB%r\fR by the song artist, \fB%b\fR by the song album, \fB%k\fR by the song number, \fB%d\fR by the song date and \fB%g\fR by the song genre\. Escaped new lines (\fB\en\fR) are also supported\. Example: \fBtitle: %t\enartist: %r\enalbum: %b\en\en\fR\.
.
.P
\fB\-d, \-\-db\fR
.
.P
\~\~\~\~\~\~ Search the MPD databse instead of the current playlist\.
.
.P
\fB\-l, \-\-list\fR
.
.P
\~\~\~\~\~\~ Create a playlist with the matching songs\.
.
.P
\fB\-a, \-\-addr\fR
.
.P
\~\~\~\~\~\~ The MPD server address\.
.
.P
\fB\-p, \-\-port\fR
.
.P
\~\~\~\~\~\~ The MPD server port\.
.
.P
\fB\-s, \-\-secret\fR
.
.P
\~\~\~\~\~\~ The MPD password\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help message\.
.
.SH "ENVIRONMENT"
\fBMPD_HOST\fR
.
.P
\~\~\~\~\~\~ The MPD server address (overridden by \fB\-\-addr\fR)\.
.
.P
\fBMPD_PORT\fR
.
.P
\~\~\~\~\~\~ The MPD server port (overridden by \fB\-\-port\fR)\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2012 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
