.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MPDIRCBOT" "1" "March 2012" "" ""
.
.SH "NAME"
\fBmpdircbot\fR \- control MPD playback through an IRC bot
.
.SH "SYNOPSIS"
\fBmpdircbot [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBmpdircbot\fR is a simple IRC bot that listens to private and channel messages and controls the MPD playback accordingly\. See \fICOMMANDS\fR for the complete list of recognized commands\.
.
.SH "OPTIONS"
\fB\-a, \-\-addr\fR
.
.P
\~\~\~\~\~\~ The MPD server address\.
.
.P
\fB\-p, \-\-port\fR
.
.P
\~\~\~\~\~\~ The MPD server port\.
.
.P
\fB\-s, \-\-secret\fR
.
.P
\~\~\~\~\~\~ The MPD password\.
.
.P
\fB\-A, \-\-irc\-addr\fR
.
.P
\~\~\~\~\~\~ The IRC server address (default \fBirc\.freenode\.net\fR)\.
.
.P
\fB\-P, \-\-irc\-port\fR
.
.P
\~\~\~\~\~\~ The IRC server port (default \fB6667\fR)\.
.
.P
\fB\-N, \-\-bot\-nick\fR
.
.P
\~\~\~\~\~\~ The IRC nick for the bot (default \fBmpdircbot\fR)\.
.
.P
\fB\-S, \-\-bot\-secret\fR
.
.P
\~\~\~\~\~\~ The password to access the bot (none by default)\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help message\.
.
.SH "COMMANDS"
The supported commands are:
.
.P
\fBplay\fR starts the playback\.
.
.P
\fBpause\fR pauses the playback\.
.
.P
\fBtoggle\fR toggles the playback\.
.
.P
\fBstop\fR stops the playback\.
.
.P
\fBprev\fR skips to the previous song\.
.
.P
\fBnext\fR skips to the next song\.
.
.P
If a password has been defined with the \fB\-\-bot\-secret\fR option, all the commands have to be prepended with that password, i\.e\. "\fIpass\fR \fIcommand\fR"\.
.
.P
If invited in a channel the bot will join it and listen to commands sent trough that channel too, so that everyone in the channel can control MPD\. To accept commands from a channel the mpdircbot nick has to be prepended to the command itself, e\.g\.:
.
.P
\fBmpdircbot, play\fR
.
.P
\fBmpdircbot, pause\fR
.
.P
\fBmpdircbot, toggle\fR
.
.P
\fB\.\.\.\fR
.
.SH "ENVIRONMENT"
\fBMPD_HOST\fR
.
.P
\~\~\~\~\~\~ The MPD server address (overridden by \fB\-\-addr\fR)\.
.
.P
\fBMPD_PORT\fR
.
.P
\~\~\~\~\~\~ The MPD server port (overridden by \fB\-\-port\fR)\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2012 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
