.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MPDIRCBOT" "1" "February 2012" "" ""
.
.SH "NAME"
\fBmpdircbot\fR \- control MPD playback through an IRC bot
.
.SH "SYNOPSIS"
\fBmpdircbot [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBmpdircbot\fR is a simple IRC bot that listens to private and channel messages and controls the MPD playback accordingly\.
.
.P
It recognizes the following commands:
.
.IP "\(bu" 4
\fBplay\fR
.
.IP "\(bu" 4
\fBpause\fR
.
.IP "\(bu" 4
\fBtoggle\fR
.
.IP "\(bu" 4
\fBstop\fR
.
.IP "\(bu" 4
\fBprev\fR
.
.IP "\(bu" 4
\fBnext\fR
.
.IP "" 0
.
.P
If invited in a channel, \fBmpdircbot\fR will join it and respond to commands sent trough the channel itself, so that everyone in the channel can control the MPD playback\. To accept commands from a channel the mpdircbot nick has to be prepended to the command itself, e\.g\.:
.
.IP "\(bu" 4
\fBmpdircbot, play\fR
.
.IP "\(bu" 4
\fBmpdircbot, pause\fR
.
.IP "\(bu" 4
\fBmpdircbot, toggle\fR
.
.IP "\(bu" 4
\&\.\.\.
.
.IP "" 0
.
.SH "OPTIONS"
\fB\-a, \-\-addr\fR
.
.P
\~\~\~\~\~\~ The MPD server address\.
.
.P
\fB\-p, \-\-port\fR
.
.P
\~\~\~\~\~\~ The MPD server port\.
.
.P
\fB\-s, \-\-secret\fR
.
.P
\~\~\~\~\~\~ The MPD password\.
.
.P
\fB\-A, \-\-irc\-addr\fR
.
.P
\~\~\~\~\~\~ The IRC server address (default \fBirc\.freenode\.net\fR)\.
.
.P
\fB\-P, \-\-irc\-port\fR
.
.P
\~\~\~\~\~\~ The IRC server port (default \fB6667\fR)\.
.
.P
\fB\-N, \-\-nick\fR
.
.P
\~\~\~\~\~\~ The IRC nick for the bot (default \fBmpdircbot\fR)\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help message\.
.
.SH "ENVIRONMENT"
\fBMPD_HOST\fR
.
.P
\~\~\~\~\~\~ The MPD server address (overridden by \fB\-\-addr\fR)\.
.
.P
\fBMPD_PORT\fR
.
.P
\~\~\~\~\~\~ The MPD server port (overridden by \fB\-\-port\fR)\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2012 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
