.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MPDLENGTH" "1" "March 2012" "" ""
.
.SH "NAME"
\fBmpdlength\fR \- print the total length of the current playlist
.
.SH "SYNOPSIS"
\fBmpdlength [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBmpdlength\fR is a simple utility that prints the total length of the current playlist or of the whole database\. The output format is customizable\.
.
.SH "OPTIONS"
\fB\-f, \-\-format\fR
.
.P
\~\~\~\~\~\~ The output format string\. See \fIFORMAT\fR for more info\.
.
.P
\fB\-d, \-\-db\fR
.
.P
\~\~\~\~\~\~ Search the MPD databse instead of the current playlist\.
.
.P
\fB\-a, \-\-addr\fR
.
.P
\~\~\~\~\~\~ The MPD server address\.
.
.P
\fB\-p, \-\-port\fR
.
.P
\~\~\~\~\~\~ The MPD server port\.
.
.P
\fB\-s, \-\-secret\fR
.
.P
\~\~\~\~\~\~ The MPD password\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help message\.
.
.SH "FORMAT"
The interpreted sequences in the format string are:
.
.P
\fB%d\fR is replaced by the number of days\.
.
.P
\fB%h\fR is replaced by the number of hours\.
.
.P
\fB%m\fR is replaced by the number of minutes\.
.
.P
\fB%s\fR is replaced by the number of seconds\.
.
.P
Example: \fB%d days, %h hours, %m mins and %s secs\fR
.
.SH "ENVIRONMENT"
\fBMPD_HOST\fR
.
.P
\~\~\~\~\~\~ The MPD server address (overridden by \fB\-\-addr\fR)\.
.
.P
\fBMPD_PORT\fR
.
.P
\~\~\~\~\~\~ The MPD server port (overridden by \fB\-\-port\fR)\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2012 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
